name: Create Release

on:
  push:
    tags:
      - "*"
permissions:
  contents: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test
        uses: rosmarinus-project/create-release@main
        with:
          body: Please refer to [CHANGELOG.md](https://github.com/rosmarinus-project/rosmarinus-universal/blob/${{ github.ref_name }}/%PROJECT_PATH%/CHANGELOG.md) for details.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}